### ISSUE TITLE
SPI class is using I2C Device

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_LSM9DS0#10]
```python
class LSM9DS0_SPI(LSM9DS0):
    """Driver for the LSM9DS0 connected over SPI."""
    # pylint: disable=no-member
    def __init__(self, spi, xmcs, gcs):
        self._gyro_device = spi_device.I2CDevice(spi, gcs)
        self._xm_device = spi_device.I2CDevice(spi, xmcs)
super().__init__()
```

**NOTE**: same issue was fixed for LSM9DS1. There, the SPI settings for phase and polarity were also incorrect. Need to check those here also.

**Comment by caternuson** [comment]
Actually, may be moot. Item is discontinued.
<https://www.adafruit.com/product/2021>

**Comment by ladyada** [comment]
it is disco'd but id like to still support it anyhow - it *just* went out of manufacture like this month and a lot of people have em

**Comment by caternuson** [comment]
Done by #11
