### ISSUE TITLE
Update functions to match design guide

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_LSM9DS0#4]
http://circuitpython.readthedocs.io/en/latest/docs/design_guide.html#sensor-properties-and-units

Currently have `accelerometer` and `magnetometer` and `gyroscope`, verify there are not more past that. Need to be updated to match design guide.

**Comment by caternuson** [comment]
Guides that will need updating:
* https://learn.adafruit.com/adafruit-lsm9ds0-accelerometer-gyro-magnetometer-9-dof-breakouts/python-circuitpython
* https://learn.adafruit.com/adding-an-accelerometer-to-you-cricket-featherwing/overview

**Comment by ladyada** [comment]
ok kattni can take a look at updating the guide!

**Comment by caternuson** [comment]
@kattni I came across this recently and self assigned this one, along with [the other one](https://github.com/adafruit/Adafruit_CircuitPython_LSM9DS1/issues/4). Mainly making notes to self here as I won't be able to get to this for a couple of weeks. If there's anything that will need updating for either, please let me know.

Also - the code fix should be pretty trivial. Maybe someone will beat me to it. :)

**Comment by tannewt** [comment]
@caternuson Can you close this now?

**Comment by caternuson** [comment]
Sure. Let's hold off on a release until #8 gets fixed.
